# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  release:
    docker:
      - image: zdvkm/node-postgres
    working_directory: ~/src
    steps:
      - checkout
      - run:
          name: 'Installing Dependencies'
          command: |
            npm install
      - run:
          name: 'Confirming Postgres Status'
          command: |
            # sudo /etc/init.d/postgresql status
            sudo service postgresql start
            sudo service postgresql status
      - run:
          name: 'Creating Database'
          command: |
            sudo -u postgres psql -p 5432 -c "create user $POSTGRES_USER with password '$POSTGRES_PASSWORD';"
            sudo -u postgres psql -p 5432 -c "alter user $POSTGRES_USER with superuser;"
            sudo -u postgres psql -p 5432 -c "create database $POSTGRES_DATABASE;"
            sudo -u postgres psql -p 5432 -c "grant all privileges on database $POSTGRES_DATABASE to $POSTGRES_USER;"
      - run:
          name: 'Running Unit Tests'
          command: |
            # npm run test:ci
            npm test
      - store_test_results:
          path: test-results
      - run:
          name: 'Running Code Coverage'
          command: |
            npm run codecov
workflows:
  version: 2
  build:
    jobs:
      - release